### ISSUE TITLE
To modifiy the sheets ?

### ISSUE THREAD

**Issue by annasmyk** [TanguyBarthelemy/JD_Tutorials#1]
Comment faire pour ... ?

how do I proceed  ?

- modifiy MD file ? then locally build ?

test screenshot paste

![image](https://github.com/TanguyBarthelemy/JD-Tutorials/assets/43274870/6b79ee9d-3382-4cff-83d4-53553dcd02c4)

![image](https://github.com/TanguyBarthelemy/JD-Tutorials/assets/43274870/7ee12708-2502-4b1f-908d-19921cb26c67)

**Comment by annasmyk** [comment]
screenshot paste seems to work but not if shot taken from this github page

**Comment by TanguyBarthelemy** [comment]
To modify the tutorials, you just have to modify the `.Rmd` pages (in the doc folder) then commit and push your modification and the building is online.

**Comment by annasmyk** [comment]
works well
